// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package inject

import (
	"context"
	"github.com/urfave/cli/v2"
	"vk-test-task/api"
)

// Injectors from wire.go:

func InitializeApplication(c *cli.Context, appCtx context.Context) (api.Container, error) {
	pool, err := createDBClient(c)
	if err != nil {
		return api.Container{}, err
	}
	injectStores := provideStores(c, pool)
	service := provideFilmotekaService(injectStores)
	authService, err := provideAuthService(injectStores)
	if err != nil {
		return api.Container{}, err
	}
	resolver := provideResolver(c, service, authService)
	container := api.NewContainer(resolver)
	return container, nil
}
